name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ganti LOCAL_DIR di build.sh
        run: |
          sed -i "s|^LOCAL_DIR=.*|LOCAL_DIR=\"$(pwd)/local\"|g" build.sh
          mkdir -p local/toolchain

      - name: Perbaiki error syntax fs.h
        run: |
          sed -i 's/);)$/);/' include/linux/fs.h

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Jalankan build.sh
        run: ./build.sh

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-zip
          path: ./*.zip
